#include <inttypes.h>
#include <stdio.h>

const char *title = "Problem 2: Even Fibonacci numbers";

const char *desc = "Each new term in the Fibonacci sequence is generated by "
"adding the previous two terms. By starting with 1 and 2, the first 10 terms "
"will be:\n\n"

"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...";

const char *question = "By considering the terms in the Fibonacci sequence "
"whose values do not exceed four million, find the sum of the even-valued "
"terms.";

int main() {
	printf("%s\n\n", title);
	printf("%s\n\n", desc);
	printf("%s\n\n", question);
	
	uint32_t sum = 0;
	
	uint32_t two_back = 1;
	uint32_t one_back = 1;
	uint32_t current = 2;
	
	while(current <= 4000000) {
		sum += current % 2 ? 0 : current;
		
		two_back = one_back;
		one_back = current;
		current = two_back + one_back;
	}
	
	printf("Solution: %" PRIu32 "\n", sum);
	return 0;
}
